# Generated by Django 2.2.1 on 2019-08-14 16:13

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import utils.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_name', models.CharField(max_length=100, verbose_name='合同名称')),
                ('crt_fileno', models.CharField(default=utils.tools.createFileNo, max_length=20, unique=True, verbose_name='合同档案号')),
                ('crt_serialnumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='合同编号')),
                ('crt_type', models.IntegerField(choices=[(1, '软件开发'), (2, '销售代理'), (3, '自有产品'), (4, '系统集成'), (5, '人员外包'), (6, '维护合同')], help_text='合同分类', verbose_name='合同分类')),
                ('crt_amt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='合同金额')),
                ('crt_currency', models.CharField(default='CNY', max_length=3, verbose_name='币种名称')),
                ('crt_salesrep', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售代表')),
                ('crt_salesarea', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售区域')),
                ('crt_signeddate', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('crt_registerdate', models.DateField(auto_now_add=True, verbose_name='登记日期')),
                ('crt_prostate', models.CharField(choices=[('00', '未开始'), ('01', '执行中'), ('02', '执行完毕'), ('03', '已取消')], default='00', max_length=2, verbose_name='执行状态')),
                ('crt_signedstate', models.CharField(choices=[('00', '未签订'), ('01', '签订中'), ('02', '已签订'), ('03', '已取消')], default='00', max_length=2, verbose_name='签订状态')),
                ('crt_effectivedate', models.DateField(blank=True, null=True, verbose_name='合同有效起始日期')),
                ('crt_enddate', models.DateField(blank=True, null=True, verbose_name='合同结束日期')),
                ('crt_desc', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='合同备注')),
                ('crt_createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('crt_updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('crt_customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_customer', to='customers.Customers', verbose_name='客户公司名称')),
            ],
            options={
                'verbose_name': '合同信息',
                'verbose_name_plural': '合同信息',
            },
        ),
    ]
