# Generated by Django 2.2.1 on 2019-08-14 16:13

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户公司名称')),
                ('customer_sh_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='客户公司简称')),
                ('customer_old_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='客户公司曾用名')),
                ('customer_addr', models.CharField(blank=True, max_length=200, null=True, verbose_name='客户公司地址')),
                ('customer_type', models.IntegerField(choices=[(1, '管理性银行'), (2, '政策性银行'), (3, '股份制商业银行'), (4, '外资银行'), (5, '城市商业银行'), (6, '城市信用社'), (7, '农联社'), (8, '村镇银行'), (9, '金融监管机构'), (10, '政府'), (11, '企业'), (12, '保险'), (13, '证券'), (14, '合作伙伴'), (15, '竞争对手'), (99, '其他')], help_text='客户类别', verbose_name='客户类别')),
                ('customer_level', models.IntegerField(choices=[(1, 'VIP客户'), (2, '战略客户'), (3, '潜力客户'), (4, '核心客户'), (5, '重要客户'), (6, '一般客户'), (7, '合作伙伴')], help_text='客户级别', verbose_name='客户级别')),
                ('customer_desc', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='客户备注')),
                ('customer_stat', models.CharField(choices=[('00', '新增待审核'), ('01', '修改待审核'), ('02', '删除待审核'), ('10', '正常'), ('20', '已删除')], default='00', max_length=2, verbose_name='客户状态')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='联系人名称')),
                ('jobtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人职位')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系人手机')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='联系人邮箱')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人传真')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customers', verbose_name='客户公司名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '客户联系人',
                'verbose_name_plural': '客户联系人',
                'ordering': ['-add_time'],
            },
        ),
    ]
