# Generated by Django 2.2.1 on 2019-08-14 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('taxes_num', models.CharField(max_length=50, verbose_name='纳税识别号')),
                ('account', models.CharField(blank=True, max_length=30, null=True, verbose_name='账号')),
                ('account_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='户名')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customers', verbose_name='客户公司名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '开票信息',
                'verbose_name_plural': '开票信息',
            },
        ),
    ]
