# Generated by Django 2.2.1 on 2019-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/', verbose_name='头像'),
        ),
    ]
